batch_size: 64
dataset_type: "hugging_face"  # ["hugging_face", "imagenet"]
dataset_name: "ENSTA-U2IS/HuskyVsWolf"
models: ["alexnet", "densenet121", "densenet169", "efficientnet", "googlelenet", "resnet18", "resnext50", "resnext101", "vgg16"]
#"inceptionv3"

train_params:
  num_epochs: 50
  save_interval: 100
  batch_size: 64

hyperparams:
  alexnet:
    lr: 1e-4
    weight_decay: 5e-4
    optimizer: "adam"

  resnet18:
    lr: 1e-3
    weight_decay: 1e-4
    optimizer: "sgd"

  vgg16:
    lr: 1e-4
    weight_decay: 5e-4
    optimizer: "adam"

  densenet121:
    lr: 5e-5
    weight_decay: 1e-4
    optimizer: "adamw"

  densenet169:
    lr: 5e-5
    weight_decay: 1e-4
    optimizer: "adamw"

  efficientnet:
    lr: 3e-5
    weight_decay: 1e-5
    optimizer: "adamw"

  googlelenet:
    lr: 1e-4
    weight_decay: 2e-4
    optimizer: "adam"

  resnext50:
    lr: 1e-3
    weight_decay: 1e-4
    optimizer: "sgd"

  resnext101:
    lr: 5e-4
    weight_decay: 1e-4
    optimizer: "sgd"

  inceptionv3: # Input size: 299x299
    lr: 1e-4
    weight_decay: 1e-4
    optimizer: "rmsprop"
